name: RELEASE-DELETE-SCHEDULE

on:
  workflow_call:
    inputs:
      APECD_REF:
        description: "The ref of apecloud-cd"
        type: string
        required: false
        default: 'main'


env:
  GH_TOKEN: ${{ github.token }}
  GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
  GITLAB_HELM_CHARTS_PROJECT_ID: 85949

jobs:
  delete-chart:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Install dateutil
        run: pip3 install python-dateutil

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkout Apecd Code
        uses: actions/checkout@v3
        with:
          repository: apecloud/apecloud-cd
          path: apecloud-cd
          ref: ${{ inputs.APECD_REF }}

      - name: delete gitlab helm chart release
        run: |
          RELEASE_VERSION=$( bash ${{ github.workspace }}/apecloud-cd/.github/utils/utils.sh --type 14 )
          
          for release in $(echo "${RELEASE_VERSION}" | sed 's/|/ /g'); do
              echo "delete release version: $release"
              bash ${{ github.workspace }}/apecloud-cd/.github/utils/release_gitlab.sh \
                  --type 6 \
                  --tag-name $release \
                  --project-id ${{ env.GITLAB_HELM_CHARTS_PROJECT_ID }} \
                  --access-token ${{ env.GITLAB_ACCESS_TOKEN }}
          done


